### PR TITLE
Will the package arch be more easy to understand?

### PR DESCRIPTION
**Pull request by IdioticMadman**

### CODE REVIEW

**Comment by erikjhordan-rey** [comment]
@IdioticMadman thanks for your contribution please only a minor inconvenience I used in my project this code style https://github.com/square/java-code-styles Could you change the code style please? it´s necessary to accept your pull-request =).

**Comment by IdioticMadman** [comment]
That's would be all right.Which style exactly? is "square" or "squareAndroid" ?

**Comment by erikjhordan-rey** [comment]
@IdioticMadman squareAndroid please!

**Comment by IdioticMadman** [comment]
@erikcaffrey Would this be okay?

**Comment by erikjhordan-rey** [comment]
@IdioticMadman thank you for your contribution there was a problem with the format of the license but I fixed cheers.

**Pull request merged**
